### ISSUE TITLE
Rotating Equipment with a quality rating makes the eqipment convert to common quality.

### ISSUE THREAD

**Issue by MrHashbrowns** [DedlySpyder/Rotatable_Equipment#1]
Crafted some rare exoskeletons and went to add them to my grid. Rotated them to make them fit and they converted to common quality.

What information would be helpful to look into this further?

**Comment by DedlySpyder** [comment]
No further info needed, I forgot quality existed when testing so makes sense it doesn't work.

**Comment by DedlySpyder** [comment]
Just uploaded 0.2.1 to fix this. Thanks for the report.
